### ISSUE TITLE
Error executing process > 'NFCORE_MASHWRAPPER:MASHWRAPPER:DOWNLOAD_GENOMES (1)'

### ISSUE THREAD

**Issue by tbazilegith** [jennahamlin/mashwrapper#7]
### Description of the bug

Hi Jenna,
Any ideas about what cause this error?
I ran this command
nextflow run mashwrapper -profile singularity --input samples_files.csv --get_database organismsheet.txt --outdir local_s2019results
It started and stopped with this error:
executor >  local (3)
[0c/0396a2] process > NFCORE_MASHWRAPPER:MASHWRAPPER:INPUT_CHECK:SAMPLESHEET_CHECK (samples_files.csv) [100%] 1 of 1 ✔
[68/81138c] process > NFCORE_MASHWRAPPER:MASHWRAPPER:ORGANISMSHEET_CHECK (organismsheet.txt)           [100%] 1 of 1 ✔
executor >  local (3)
[0c/0396a2] process > NFCORE_MASHWRAPPER:MASHWRAPPER:INPUT_CHECK:SAMPLESHEET_CHECK (samples_files.csv) [100%] 1 of 1 ✔
[68/81138c] process > NFCORE_MASHWRAPPER:MASHWRAPPER:ORGANISMSHEET_CHECK (organismsheet.txt)           [100%] 1 of 1 ✔
[40/1d7b33] process > NFCORE_MASHWRAPPER:MASHWRAPPER:DOWNLOAD_GENOMES (1)                              [100%] 1 of 1, failed: 1 ✘
[-        ] process > NFCORE_MASHWRAPPER:MASHWRAPPER:MAKE_MASH                                         -
[-        ] process > NFCORE_MASHWRAPPER:MASHWRAPPER:MAKE_DATABASE                                     -
[-        ] process > NFCORE_MASHWRAPPER:MASHWRAPPER:SPECIES_ID                                        -
[-        ] process > NFCORE_MASHWRAPPER:MASHWRAPPER:COMBINED_OUTPUT                                   -
[-        ] process > NFCORE_MASHWRAPPER:MASHWRAPPER:CUSTOM_DUMPSOFTWAREVERSIONS                       -
Execution cancelled -- Finishing pending tasks before exit
executor >  local (3)
[0c/0396a2] process > NFCORE_MASHWRAPPER:MASHWRAPPER:INPUT_CHECK:SAMPLESHEET_CHECK (samples_files.csv) [100%] 1 of 1 ✔
[68/81138c] process > NFCORE_MASHWRAPPER:MASHWRAPPER:ORGANISMSHEET_CHECK (organismsheet.txt)           [100%] 1 of 1 ✔
[40/1d7b33] process > NFCORE_MASHWRAPPER:MASHWRAPPER:DOWNLOAD_GENOMES (1)                              [100%] 1 of 1, failed: 1 ✘
[-        ] process > NFCORE_MASHWRAPPER:MASHWRAPPER:MAKE_MASH                                         -
[-        ] process > NFCORE_MASHWRAPPER:MASHWRAPPER:MAKE_DATABASE                                     -
[-        ] process > NFCORE_MASHWRAPPER:MASHWRAPPER:SPECIES_ID                                        -
[-        ] process > NFCORE_MASHWRAPPER:MASHWRAPPER:COMBINED_OUTPUT                                   -
[-        ] process > NFCORE_MASHWRAPPER:MASHWRAPPER:CUSTOM_DUMPSOFTWAREVERSIONS                       -
Execution cancelled -- Finishing pending tasks before exit
-[jennahamlin/mashwrapper] Pipeline completed with errors-

                Results will not be emailed. 
                Please check your specified out directory for the results. 
                Your results folder is called: local_s2019results
                
WARN: Graphviz is required to render the execution DAG in the given format -- See http://www.graphviz.org for more info.
Error executing process > 'NFCORE_MASHWRAPPER:MASHWRAPPER:DOWNLOAD_GENOMES (1)'

Caused by:
  Missing output file(s) `*.fna` expected by process `NFCORE_MASHWRAPPER:MASHWRAPPER:DOWNLOAD_GENOMES (1)`

Command executed:
Thanks!

**Comment by jennahamlin** [comment]
@tbazilegith 

Were you able to successfully run the test dataset for getting genomes and running the test (testGet)? 
`nextflow run mashwrapper -profile testGet,YOURPROFILE `

Additionally, when I run the tool I have to include a configuration file to specify certificates which is located here: https://github.com/jennahamlin/mashwrapper/blob/main/conf/nfcore_custom.config

My command looks like this: 
`nextflow run mashwrapper -profile testGet,singularity  --custom_config_base /scicomp/home-pure/ptx4/mashwrapper/conf`

Though you would need to change the path to the configuration file to whatever is specific for you.

**Comment by tbazilegith** [comment]
Hi Jenna,
Thanks for the reply! 
The tool ran successfully with testUse (nextflow run mashwrapper -profile testUse,singularity ), but didn't with testGet.
below is the command I used
nextflow run mashwrapper -profile testGet,singularity  --custom_config_base mashwrapper/conf (my working dir is parent to mashwrapper/)
1st I got this
WARNING: Could not load nf-core/config profiles: mashwrapper/conf/nfcore_custom.config
2nd, here is the error (sorry it's long)

* Software dependencies
  https://github.com/jennahamlin/mashwrapper/blob/master/CITATIONS.md
------------------------------------------------------
executor >  local (7)
[f8/c51c63] process > NFCORE_MASHWRAPPER:MASHWRAPPER:INPUT_CHECK:SAMPLESHEET_CHECK (inputReads.csv) [100%] 1 of 1 â
[dc/7adb8f] process > NFCORE_MASHWRAPPER:MASHWRAPPER:ORGANISMSHEET_CHECK (inputDB.txt)              [100%] 1 of 1 â
[d0/ef55dd] process > NFCORE_MASHWRAPPER:MASHWRAPPER:DOWNLOAD_GENOMES (1)                           [ 83%] 5 of 6, failed: 5
[-        ] process > NFCORE_MASHWRAPPER:MASHWRAPPER:MAKE_MASH                                      -
[-        ] process > NFCORE_MASHWRAPPER:MASHWRAPPER:MAKE_DATABASE                                  -
[-        ] process > NFCORE_MASHWRAPPER:MASHWRAPPER:SPECIES_ID                                     -
[-        ] process > NFCORE_MASHWRAPPER:MASHWRAPPER:COMBINED_OUTPUT                                -
[-        ] process > NFCORE_MASHWRAPPER:MASHWRAPPER:CUSTOM_DUMPSOFTWAREVERSIONS                    -
Execution cancelled -- Finishing pending tasks before exit
-[jennahamlin/mashwrapper] Pipeline completed with errors-

                Results will not be emailed.
                Please check your specified out directory for the results.
                Your results folder is called: ./results

WARN: Graphviz is required to render the execution DAG in the given format -- See http://www.graphviz.org for more info.
Error executing process > 'NFCORE_MASHWRAPPER:MASHWRAPPER:DOWNLOAD_GENOMES (5)'

Caused by:
  Process `NFCORE_MASHWRAPPER:MASHWRAPPER:DOWNLOAD_GENOMES (5)` terminated with an error exit status (1)

Command executed:

  ## Original downloadGenome.sh script allows user to specify using conda
  ## environment, incorporate a boolean for conda to be used with -c flag

  ## export nf variable to tell downloadGenome script if nextflow is in use
  nf="This is script is running via NextFlow"
  export nf

  if [[ "false" != false ]]; then
      /blue/bphl-florida/t.bazile1/aphl_bi_fellow/data/legionella/mashwrapper_dir/mashwrapper/bin/downloadGenome.sh -c "false" -s "legionella oakridgensis" -a "false"
  else
      /blue/bphl-florida/t.bazile1/aphl_bi_fellow/data/legionella/mashwrapper_dir/mashwrapper/bin/downloadGenome.sh -c "false" -s "legionella oakridgensis"
  fi

  cat <<-END_VERSIONS > versions.yml
  "NFCORE_MASHWRAPPER:MASHWRAPPER:DOWNLOAD_GENOMES":
      datasets: $(datasets version | sed 's/Datasets //g')
      dataformat: $(dataformat version | sed 's/Dataformat //g')
  END_VERSIONS

Command exit status:
  1

Command output:
  Confirming both NCBI datasets/dataformat tools and Mash are available...

Command error:
  Confirming both NCBI datasets/dataformat tools and Mash are available...
  NCBI dataformat is not installed.  Exiting.

Thanks,
TJ

**Comment by jennahamlin** [comment]
Hi TJ-

For the test dataset and to use the custom config file, you must specify the full path to the file but not the file name, so this would not work: --custom_config_base mashwrapper/conf  while this works for me: --custom_config_base /scicomp/home-pure/ptx4/mashwrapper/conf and this is what I get when I am in conf folder within mashwrapper and I pwd

**Comment by tbazilegith** [comment]
Hi Jenna,
Thank you so much!
It worked.
-[jennahamlin/mashwrapper] Pipeline completed successfully-

So, does that suggest I have to provide the full path of the custom config - when I use my own data?
- Will the tool download data and create the mash sketch when I provide the species name is organism-sheet.txt file?
-Thank you again?
TJ

**Comment by tbazilegith** [comment]
It works well. Thanks!

**Comment by jennahamlin** [comment]
@tbazilegith glad you were able to get it working:)
